
services:
  hrd_app:
    container_name: hrd_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    volumes:
      - static_volume:/app/static
    command: sh -c "sleep 3 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn --workers 3 hrd.wsgi:application --bind 0.0.0.0:8000"
volumes:
  static_volume:
  
  # nama:
  #   external: true


# 192.168.144.3'