version: "3.8"

services:
  hrd_app:
    container_name: hrd_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - static_volume:/static
      - /home/azril/ahris/ahris/hrd:/app/hrd
    command: sh -c "sleep 3 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn --workers 3 hrd.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DB_NAME: root
      DB_PASS: ""
      DB_HOST: mysql
      DB_PORT: 3306
    networks:
      - ndb

volumes:
  static_volume:
  
  # nama:
  #   external: true


# 192.168.144.3'