# Generated by Django 5.0.6 on 2024-07-05 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='awal_cuti_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField(null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Awal Cuti',
                'verbose_name_plural': 'Awal Cuti',
            },
        ),
        migrations.CreateModel(
            name='counter_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counter',
            },
        ),
        migrations.CreateModel(
            name='data_raw_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('jam_absen', models.DateTimeField(blank=True, null=True)),
                ('punch', models.IntegerField(blank=True, null=True)),
                ('mesin', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_trans_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('jam_absen', models.DateTimeField(blank=True, null=True)),
                ('punch', models.IntegerField(blank=True, null=True)),
                ('mesin', models.CharField(max_length=100, null=True)),
                ('keterangan', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='datamesin_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('nama', models.CharField(max_length=100, null=True)),
                ('userid', models.CharField(max_length=100, null=True, unique=True)),
                ('level', models.IntegerField()),
                ('password', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Data Mesin',
                'verbose_name_plural': 'Data Mesin',
            },
        ),
        migrations.CreateModel(
            name='divisi_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisi', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Divisi',
                'verbose_name_plural': 'Divisi',
            },
        ),
        migrations.CreateModel(
            name='hari_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nama Hari',
                'verbose_name_plural': 'Nama Hari',
            },
        ),
        migrations.CreateModel(
            name='histori_hapus_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_by', models.CharField(max_length=100, null=True)),
                ('delete_item', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Histori Hapus',
                'verbose_name_plural': 'Histori Hapus',
            },
        ),
        migrations.CreateModel(
            name='jabatan_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Jabatan',
                'verbose_name_plural': 'Jabatan',
            },
        ),
        migrations.CreateModel(
            name='jenis_ijin_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_ijin', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Jenis Ijin',
                'verbose_name_plural': 'Jenis Ijin',
            },
        ),
        migrations.CreateModel(
            name='kelompok_kerja_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kelompok Kerja',
                'verbose_name_plural': 'Kelompok Kerja',
            },
        ),
        migrations.CreateModel(
            name='kota_kabupaten_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_koka', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='last_te',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('jam', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Last data today enrollment',
                'verbose_name_plural': 'Last data today enrollment',
            },
        ),
        migrations.CreateModel(
            name='libur_nasional_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libur', models.CharField(max_length=100)),
                ('tgl_libur', models.DateField()),
                ('insentif_karyawan', models.IntegerField(blank=True, default=20000, null=True)),
                ('insentif_staff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libur Nasional',
                'verbose_name_plural': 'Libur Nasional',
            },
        ),
        migrations.CreateModel(
            name='mesin_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('ipaddress', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Non Active', 'Non Active')], default='Active', max_length=100)),
            ],
            options={
                'verbose_name': 'Mesin',
                'verbose_name_plural': 'Mesin',
            },
        ),
        migrations.CreateModel(
            name='rp_lembur_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rupiah', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rupiah Lembur',
                'verbose_name_plural': 'Rupiah Lembur',
            },
        ),
        migrations.CreateModel(
            name='sidikjari_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('nama', models.CharField(max_length=100, null=True)),
                ('userid', models.CharField(max_length=100, null=True)),
                ('size', models.IntegerField()),
                ('fid', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('template', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Sidik Jari',
                'verbose_name_plural': 'Sidik Jari',
            },
        ),
        migrations.CreateModel(
            name='status_pegawai_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Status Pegawai',
                'verbose_name_plural': 'Status Pegawai',
            },
        ),
        migrations.CreateModel(
            name='tarik_terakhir_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('jam', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarik Terakhir',
                'verbose_name_plural': 'Tarik Terakhir',
            },
        ),
        migrations.CreateModel(
            name='tutup_toko_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(blank=True, max_length=50, null=True)),
                ('jam_tutup', models.TimeField()),
            ],
            options={
                'verbose_name': 'Jam Tutup Toko',
                'verbose_name_plural': 'Jam Tutup Toko',
            },
        ),
        migrations.CreateModel(
            name='akses_divisi_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.divisi_db')),
            ],
        ),
        migrations.CreateModel(
            name='jamkerja_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_masuk', models.TimeField(null=True)),
                ('jam_pulang', models.TimeField(null=True)),
                ('jam_istirahat', models.TimeField(null=True)),
                ('jam_kembali_istirahat', models.TimeField(null=True)),
                ('jam_istirahat2', models.TimeField(null=True)),
                ('jam_kembali_istirahat2', models.TimeField(null=True)),
                ('hari', models.CharField(choices=[('Semua Hari', 'Semua Hari'), ('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=50)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('kk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.kelompok_kerja_db')),
            ],
            options={
                'verbose_name': 'Jam Kerja',
                'verbose_name_plural': 'Jam Kerja',
            },
        ),
        migrations.CreateModel(
            name='pegawai_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('userid', models.CharField(max_length=100, null=True, unique=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('nik', models.CharField(max_length=100, null=True)),
                ('no_rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('no_bpjs_ks', models.CharField(blank=True, max_length=50, null=True)),
                ('no_bpjs_tk', models.CharField(blank=True, max_length=50, null=True)),
                ('payroll_by', models.CharField(choices=[('Owner', 'Owner'), ('HRD', 'HRD'), ('Lainnya', 'Lainnya')], default='HRD', max_length=50)),
                ('ks_premi', models.IntegerField(default=0)),
                ('tk_premi', models.IntegerField(default=0)),
                ('aktif', models.IntegerField(null=True)),
                ('tgl_masuk', models.DateField(blank=True, null=True)),
                ('tgl_aktif', models.DateTimeField(blank=True, null=True)),
                ('tgl_nonaktif', models.DateTimeField(blank=True, null=True)),
                ('sisa_cuti', models.IntegerField(null=True)),
                ('shift', models.CharField(blank=True, max_length=100, null=True)),
                ('rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('add_by', models.CharField(blank=True, max_length=100, null=True)),
                ('edit_by', models.CharField(blank=True, max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('item_edit', models.CharField(blank=True, max_length=100, null=True)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.counter_db')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.divisi_db')),
                ('hari_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.hari_db')),
                ('hari_off2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hari_off2', to='hrd_app.hari_db')),
                ('jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.jabatan_db')),
                ('kelompok_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.kelompok_kerja_db')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.status_pegawai_db')),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
            },
        ),
        migrations.CreateModel(
            name='opg_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opg_tgl', models.DateField(null=True)),
                ('diambil_tgl', models.DateField(null=True)),
                ('keterangan', models.TextField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'OPG',
                'verbose_name_plural': 'OPG',
            },
        ),
        migrations.CreateModel(
            name='lembur_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_lembur', models.DateField()),
                ('lembur_awal', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('lembur_akhir', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('istirahat', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('istirahat2', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('lebih_nproses', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('proses_lembur', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('status', models.IntegerField(default=0)),
                ('keterangan', models.TextField(null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Lembur',
                'verbose_name_plural': 'Lembur',
            },
        ),
        migrations.CreateModel(
            name='kontak_lain_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubungan', models.CharField(max_length=30, null=True)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Orang yg dapat dihubungi',
                'verbose_name_plural': 'Orang yg dapat dihubungi',
            },
        ),
        migrations.CreateModel(
            name='kompen_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_kompen', models.DateField()),
                ('kompen', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('jenis_kompen', models.CharField(choices=[('Awal', 'Awal'), ('Akhir', 'Akhir'), ('1 Hari', '1 Hari')], max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Kompensasi',
                'verbose_name_plural': 'Kompensasi',
            },
        ),
        migrations.CreateModel(
            name='keluarga_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubungan', models.CharField(max_length=30, null=True)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('tgl_lahir', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('gol_darah', models.CharField(max_length=5, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Data Keluarga',
                'verbose_name_plural': 'Data Keluarga',
            },
        ),
        migrations.CreateModel(
            name='ijin_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_ijin', models.DateField(null=True)),
                ('keterangan', models.TextField(null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('ijin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.jenis_ijin_db')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Ijin Pegawai',
                'verbose_name_plural': 'Ijin Pegawai',
            },
        ),
        migrations.CreateModel(
            name='geseroff_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dari_tgl', models.DateField()),
                ('ke_tgl', models.DateField()),
                ('keterangan', models.TextField(null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Geser OFF',
                'verbose_name_plural': 'Geser OFF',
            },
        ),
        migrations.CreateModel(
            name='dinas_luar_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_dinas', models.DateField(null=True)),
                ('keterangan', models.TextField(null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Dinas Luar',
                'verbose_name_plural': 'Dinas Luar',
            },
        ),
        migrations.CreateModel(
            name='cuti_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_cuti', models.DateField()),
                ('cuti_ke', models.IntegerField(default=0)),
                ('keterangan', models.TextField(null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Cuti',
                'verbose_name_plural': 'Cuti',
            },
        ),
        migrations.CreateModel(
            name='absensi_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_absen', models.DateField()),
                ('masuk', models.TimeField(null=True)),
                ('istirahat', models.TimeField(null=True)),
                ('kembali', models.TimeField(null=True)),
                ('istirahat2', models.TimeField(null=True)),
                ('kembali2', models.TimeField(null=True)),
                ('pulang', models.TimeField(null=True)),
                ('masuk_b', models.TimeField(null=True)),
                ('istirahat_b', models.TimeField(null=True)),
                ('kembali_b', models.TimeField(null=True)),
                ('istirahat2_b', models.TimeField(null=True)),
                ('kembali2_b', models.TimeField(null=True)),
                ('pulang_b', models.TimeField(null=True)),
                ('keterangan_absensi', models.TextField(null=True)),
                ('keterangan_ijin', models.TextField(null=True)),
                ('keterangan_lain', models.TextField(null=True)),
                ('libur_nasional', models.CharField(max_length=100, null=True)),
                ('insentif', models.IntegerField(default=0)),
                ('jam_masuk', models.TimeField(null=True)),
                ('lama_istirahat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lama_istirahat2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('jam_pulang', models.TimeField(null=True)),
                ('jam_istirahat', models.FloatField(null=True)),
                ('total_jam_kerja', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('total_jam_istirahat', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('total_jam_istirahat2', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('lebih_jam_kerja', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
            },
        ),
        migrations.CreateModel(
            name='pendidikan_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan', models.CharField(choices=[('KULIAH', 'KULIAH'), ('SMK/SMA', 'SMK/SMA'), ('SMP', 'SMP')], max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('dari_tahun', models.DateField()),
                ('sampai_tahun', models.DateField()),
                ('jurusan', models.CharField(max_length=50, null=True)),
                ('gelar', models.CharField(max_length=50, null=True)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.kota_kabupaten_db')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Pendidikan',
                'verbose_name_plural': 'Pendidikan',
            },
        ),
        migrations.CreateModel(
            name='pengalaman_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perusahaan', models.CharField(max_length=50)),
                ('dari_tahun', models.DateField()),
                ('sampai_tahun', models.DateField()),
                ('jabatan', models.CharField(max_length=50)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.kota_kabupaten_db')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Pengalaman Kerja',
                'verbose_name_plural': 'Pengalaman Kerja',
            },
        ),
        migrations.CreateModel(
            name='pribadi_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('kota_lahir', models.CharField(max_length=200, null=True)),
                ('tgl_lahir', models.DateField(null=True)),
                ('tinggi_badan', models.FloatField(default=0)),
                ('berat_badan', models.FloatField(default=0)),
                ('gol_darah', models.CharField(max_length=5, null=True)),
                ('agama', models.CharField(max_length=30, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Data Pribadi',
                'verbose_name_plural': 'Data Pribadi',
            },
        ),
        migrations.CreateModel(
            name='promosi_demosi_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Promosi', 'Promosi'), ('Demosi', 'Demosi')], max_length=100, null=True)),
                ('jabatan_sebelum', models.CharField(max_length=50, null=True)),
                ('jabatan_sekarang', models.CharField(max_length=50, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Promsi / Demosi',
                'verbose_name_plural': 'Promsi / Demosi',
            },
        ),
        migrations.CreateModel(
            name='rekap_lembur_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('total_lembur', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('total_kompen', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('sisa_lembur', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('lembur_jam_bayar', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('lembur_rupiah_bayar', models.IntegerField(default=0, null=True)),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Rekap Lembur',
                'verbose_name_plural': 'Rekap Lembur',
            },
        ),
        migrations.CreateModel(
            name='sangsi_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_berlaku', models.DateField(null=True)),
                ('status_sangsi', models.CharField(choices=[('SP1', 'SP1'), ('SP2', 'SP2'), ('SP3', 'SP3')], max_length=50, null=True)),
                ('deskripsi_pelanggaran', models.TextField(null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
            ],
            options={
                'verbose_name': 'Promsi / Demosi',
                'verbose_name_plural': 'Promsi / Demosi',
            },
        ),
        migrations.CreateModel(
            name='list_status_opg_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_by', models.CharField(max_length=100, null=True)),
                ('edit_by', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.status_pegawai_db')),
            ],
            options={
                'verbose_name': 'Status Pegawai yang dapat OPG',
                'verbose_name_plural': 'Status Pegawai yang dapat OPG',
            },
        ),
        migrations.CreateModel(
            name='akses_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akses', models.CharField(choices=[('root', 'root'), ('admin', 'admin'), ('it', 'it'), ('user', 'user'), ('tamu', 'tamu')], default='user', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.pegawai_db')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.status_pegawai_db')),
            ],
        ),
        migrations.CreateModel(
            name='status_pegawai_lembur_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.status_pegawai_db')),
            ],
            options={
                'verbose_name': 'Status Pegawai yg Lembur',
                'verbose_name_plural': 'Status Pegawai yg Lembur',
            },
        ),
        migrations.CreateModel(
            name='status_pegawai_lintas_hari_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.status_pegawai_db')),
            ],
            options={
                'verbose_name': 'Status Pegawai yg Lintas Hari',
                'verbose_name_plural': 'Status Pegawai yg Lintas Hari',
            },
        ),
    ]
