# Generated by Django 5.0.6 on 2024-07-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0002_kota_kabupaten_db_id_provinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai_db',
            name='cuti_awal',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='promodemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_berlaku', models.DateField(null=True)),
                ('jabatan_sebelum', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_sebelum', to='hrd_app.jabatan_db')),
                ('jabatan_setelah', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_setelah', to='hrd_app.jabatan_db')),
            ],
        ),
    ]
