# Generated by Django 5.0.6 on 2024-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0003_pegawai_db_cuti_awal_promodemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promosi_demosi_db',
            name='tgl',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='promodemo',
        ),
    ]
