# Generated by Django 5.0.6 on 2024-07-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0004_promosi_demosi_db_tgl_delete_promodemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promosi_demosi_db',
            name='jabatan_sebelum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_sebelum', to='hrd_app.jabatan_db'),
        ),
        migrations.AlterField(
            model_name='promosi_demosi_db',
            name='jabatan_sekarang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_setelah', to='hrd_app.jabatan_db'),
        ),
    ]
