# Generated by Django 5.0.6 on 2024-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0005_alter_promosi_demosi_db_jabatan_sebelum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangsi_db',
            name='tgl_berakhri',
            field=models.DateField(null=True),
        ),
    ]
