# Generated by Django 5.0.6 on 2024-07-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0006_sangsi_db_tgl_berakhri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sangsi_db',
            old_name='tgl_berakhri',
            new_name='tgl_berakhir',
        ),
    ]
